name: Q2 Workflow

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Q2_archive_README.md
        run: |
          echo "Nom: Lorenzo DE MACEDO" > Q2_archive_README.md
          echo "Date: $(date)" >> Q2_archive_README.md
          cat README.md >> Q2_archive_README.md

      - name: Push new file
        run: |
          git config user.name "LorenzoDMFR"
          git config user.email "lorenzo-de.macedo@etu.univ-lehavre.fr"
          git add Q2_archive_README.md
          git commit -m "Add Q2_archive_README.md"
          git push
